version: '3'
services:
  trilium:
    image: zadam/trilium
    restart: unless-stopped
    volumes:
      - trilium-data:/home/node/trilium-data
    ports:
      - 8081:8080
    deploy:
      #labels:
        #- "traefik.enable=true"
        #- "traefik.http.routers.trilium.rule= Host(`trilium.casa`)"
        #- "traefik.http.routers.trilium.middlewares=trilium_path@docker"
        #- "traefik.http.middlewares.trilium_path.replacepathregex.regex=/trilium(.*)"
        #- "traefik.http.middlewares.trilium_path.replacepathregex.replacement=$$1"
        #- "traefik.http.services.trilium.loadbalancer.server.port=8080"
      placement:
        constraints:
          - node.labels.type!=nas

volumes:
  trilium-data:
