# Running `docker-compose up` will create/use the "trilium-data" directory in the user home
# Run `TRILIUM_DATA_DIR=/path/of/your/choice docker-compose up` to set a different directory
version: '2.1'
services:
  trilium:
    image: zadam/trilium
    restart: always
    environment:
      - trillium=/home/node/trilium-data
    ports:
      - "8080:8080"
    volumes:
      - trillium:/home/node/trilium-data
    deploy:
      placement:
        constraints:
          - node.labels.type==worker

volumes:
  trilium:
